### ISSUE TITLE
 Travis :  Type not found : haxe.crypto.Aes

### ISSUE THREAD

**Issue by flashultra** [HaxeFoundation/crypto#1]
**AesTest.hx**  failed on import with  error "**Type not found : haxe.crypto.Aes**".

  I  think the problem is because haxe compiler search in his repository in haxe.crypto package , but Aes class exist in same package haxe.crypto , but in crypto repository .  

  I set classpath in  https://github.com/HaxeFoundation/crypto/blob/master/tests/compile.hxml  to be "src" and "../src" , but it doesn't help.

For me , package haxe.crypto is logical choice for crypto repository data, for severa reasons:
 1) If old projects install crypto package , they still can use Hmac, Sha256 , Sha224  without to change any code.
2) Crypto repository can be consider as  crypto+ against haxe.crypto in haxe repository and both can work in parallel

**Comment by andyli** [comment]
The actual problems are:
 1. the `AES.hx` file used a different case then the `Aes` class
 2. missing `-p ../src` in `tests/compile-each.hxml`

**Comment by flashultra** [comment]
Thank you @andyli !  It's fixed , but something else happend:
```
$ haxe compile.hxml
/bin/sh: 1: mxmlc: not found
Error: Command failed with error 127
```

Could you give some advice ?

**Comment by andyli** [comment]
> mxmlc: not found

That's just because there is no mxmlc installed in our CI script. I would suggest commending out any call to mxmlc since there is little use of the AS3 target.
