### ISSUE TITLE
Does it support Aes-256 bit

### ISSUE THREAD

**Issue by r8code** [HaxeFoundation/crypto#10]
It said support Aes , but does not mention which one
does the default is 256 bit , or which one ?
if supported , how to set it ?

**Comment by flashultra** [comment]
Yes , it support all AES key sizes - 128,192,256 bits.
If you want to use AES - 256 bits , just set encryption  key with size 256 btis. 
At example:
```haxe
var aes : Aes = new Aes();
  
// this key is 32 bytes or  256 bits 
  var key = Bytes.ofHex("603DEB1015CA71BE2B73AEF0857D77811F352C073B6108D72D9810A30914DFF4");
  var text = Bytes.ofString("Haxe - The Cross-platform Toolkit");
  var iv:Bytes = Bytes.ofHex("4F021DB243BC633D7178183A9FA071E8");
  
  aes.init(key,iv);
  
  // Encrypt
  var data = aes.encrypt(Mode.CTR,text,Padding.NoPadding);
  trace("Encrypted text: "+ data.toHex());
```
Or you can use any password and convert it to 256-bits using SHA-256 :
```var key = Sha256.make("secret password");```

For 192-bits you can use:
  ```var key = Bytes.ofHex("8e73b0f7da0e6452c810f32b809079e562f8ead2522c6b7b");```

and for 128-bits:
 ```var key = Bytes.ofHex("2b7e151628aed2a6abf7158809cf4f3c");```

Hope that helps.

**Comment by r8code** [comment]
Thank you for the detailed answers
