### ISSUE TITLE
Error "haxe.io.Bytes should be String"

### ISSUE THREAD

**Issue by khalyomede** [HaxeFoundation/crypto#15]
## Description

I want to secure session related data by encrypting it, and being able to retreive it by decrypting it.

I ran into an error trying to run this snippet (taken from the README example)

```haxe
import haxe.io.Bytes;
import haxe.crypto.mode.Mode;
import haxe.crypto.padding.Padding;
import haxe.crypto.Aes;

@:nullSafety(Strict)
final class Main {
  static var key = "";

  public static function main() {
    final aes : Aes = new Aes();

    final key = Bytes.ofHex("603DEB1015CA71BE2B73AEF0857D77811F352C073B6108D72D9810A30914DFF4");
    final text = Bytes.ofString("Haxe - The Cross-platform Toolkit");
    final iv: Bytes = Bytes.ofHex("4F021DB243BC633D7178183A9FA071E8");

    aes.init(key,iv);

    // Encrypt
    final data = aes.encrypt(Mode.CTR, text, Padding.NoPadding);
  }
}
```

And I get this error:

> haxe.io.Bytes should be String

Around the last line (I supposed it is related to the second parameter.

## Additional data

- Haxe version: 4.1.5
- Target: PHP
- Package version: 0.3.0 and 1.0.2-alpha
- OS: Alpine (over Docker for Windows 10)

**Comment by kLabz** [comment]
How are you using `data`? I don't get any error with your code, but `aes.encrypt()` produces `haxe.io.Bytes`, and if data is expected to be of `String` type you'd get this error.

What is the exact error position, by the way? The `characters X-XX` part should help figuring out if it's the second parameter or the whole expression.

**Comment by flashultra** [comment]
I also run  the example without a problem. 
 Could you tell me what version of Haxe you use ( mine is 4.1.4 ) and which target you tried ( eval, js, python , etct) ?

**Comment by khalyomede** [comment]
Thanks guys for taking your time to check on this one, I updated the description with these info:
- Haxe version: 4.1.5
- Target: PHP

I confirm this does not occur when using haxe as the interpreter.

@kLabz I am storing the data in the rest of my code (I can paste the whole code if you are interested in the full snippet, it is part of a library to manage sessions for PHP using Haxe).

**Edit**: Dumb me, it was just a type error on my end, you were right @kLabz thanks!
