### ISSUE TITLE
SHA-256 is wrong on PHP (new Haxelib release needed)

### ISSUE THREAD

**Issue by CedX** [HaxeFoundation/crypto#17]
Haxe 4.2.4 / PHP 8.1.0 with `crypto` 1.0.2-alpha.

If I generate a SHA-256 hash code using the PHP `hash` function:

```haxe
trace(php.Global.hash("sha256", "FooBar123"));
// 77853caf12f9d2020f3715accd9c7b15738705daf03650906af17a7a655c2ee2
```

If I generate the same SHA-256 hash code using the `haxe.crypto.Sha256` class... **without** the `crypto` library enabled:

```haxe
trace(haxe.crypto.Sha256.encode("FooBar123"));
// 77853caf12f9d2020f3715accd9c7b15738705daf03650906af17a7a655c2ee2
```

If I generate the same SHA-256 hash code using the `haxe.crypto.Sha256` class... **with** the `crypto` library enabled:

```haxe
trace(haxe.crypto.Sha256.encode("FooBar123"));
// c029836676a2e454cdafcd48507c211c8d52f0e06db9bd6d7a409fcf970f57c6 => What?!?
```

It seems that PR #12 was not released on Haxelib...
https://lib.haxe.org/p/crypto/1.0.2-alpha/files/crypto-1.0.2-alpha/src/haxe/crypto/Sha256.hx

...and it seems that there is a difference between the implementations provided by this package and the Haxe standard library.

**Comment by flashultra** [comment]
The problem is with bitwise shift left operation in PHP ( and Python) as it is mention here : 
 https://github.com/HaxeFoundation/haxe/issues/7533

For example , this:  ```1634873650 << 25``` will return ```C2E46264000000``` in PHP, but ```64000000``` on other targets.
One possible solution could be to apply mask 0xFFFFFFFF for each bitwise left operation ( for PHP target)
About PR #12 , yes it's not released yet.

The last version is  crypto 0.3.0 ( for some reason alpha is before the last one).

**Comment by CedX** [comment]
Fixed by [version 0.4.0](https://lib.haxe.org/p/crypto/0.4.0/): thanks @flashultra!

**Comment by flashultra** [comment]
Are you sure about the results using SHA-256 hash code without the crypto enabled ?
I did some tests and also compare   [the code](https://github.com/HaxeFoundation/haxe/blob/development/std/haxe/crypto/Sha256.hx)  and it returns wrong value for me -> c029836676a2e454cdafcd48507c211c8d52f0e06db9bd6d7a409fcf970f57c6  ( this is without crypto lib)

**Comment by CedX** [comment]
I confirm that the `haxe.crypto.Sha256` class from the standard library returns the right value... at least with my setup (Haxe 4.2.4 / PHP 8.1.0 on Windows 10, also tested successfully on CentOS 8).

Minimal repro:

```haxe
// File "Main.hx"
import haxe.crypto.Sha256;
import php.Global;

function main() {
	trace(Global.hash("sha256", "FooBar123"));
	trace(Sha256.encode("FooBar123"));
}
```

With this command:

```shell
haxe --main Main --php . --cmd "php index.php"
```

Output:

```shell
Main.hx:6: 77853caf12f9d2020f3715accd9c7b15738705daf03650906af17a7a655c2ee2
Main.hx:7: 77853caf12f9d2020f3715accd9c7b15738705daf03650906af17a7a655c2ee2
```

**Comment by CedX** [comment]
I made a quick diff between the 2 implementations, and there is some differences in `Sha256.str2blks()` method (`crypto` on left, stdlib on right):

![image](https://user-images.githubusercontent.com/1643950/145688730-5122cfc0-1392-4954-80a7-210ea66bdf5e.png)

**Comment by flashultra** [comment]
Maybe I'm going crazy, but you can make one little test:
 1) Copy original [ Sha256.hx](https://github.com/HaxeFoundation/haxe/blob/development/std/haxe/crypto/Sha256.hx) file in new subfolder  /haxe/crypto/ where your Main.hx file is.
 2) Compile to php
 3) Run the test
 So your directory structure should be 
```
 | -- Main.hx
 |---haxe/
    |-crypto/
         |----Sha256.hx
```
The idea is to use  the local file ( which should be the same as Sha256.hx in  Haxetoolkit

**Comment by CedX** [comment]
Whoa! Really weird... Effectively, if I make a local copy, the SHA-256 is wrong and results in:
`c029836676a2e454cdafcd48507c211c8d52f0e06db9bd6d7a409fcf970f57c6`

If I remove or rename the local copy, the result is:
`77853caf12f9d2020f3715accd9c7b15738705daf03650906af17a7a655c2ee2`

But there is of course an explanation...
After checking the generated files, I saw that, without a local copy, the compiler use this file in the final output:
https://github.com/HaxeFoundation/haxe/blob/development/std/php/_std/haxe/crypto/Sha256.hx

**Comment by flashultra** [comment]
Yes, php target obviously uses a native function .
Well , the problem ( for int32)  with the shift left operation still remains and could cause another function to fail , but we'll see.
