### ISSUE TITLE
Need PKCS5 Padding

### ISSUE THREAD

**Issue by rat-moonshine** [HaxeFoundation/crypto#19]
Please provide support for PKCS5 padding. Currently it supports only PKCS7.

A reference to [PKCS5](https://github.com/Atmosphere/ActionScript/blob/master/src/com/hurlant/crypto/symmetric/PKCS5.as) can be found on sowyiz.crypto.

**Comment by flashultra** [comment]
You can use PKCS7 as replacement for PKCS5 padding , it's the same with only difference in block size. 
PKCS5 is only for 8-byte  block size;
PKCS7 support block size from 1 to 255 bytes.
So  PKCS5 padding is a subset of PKCS7 padding for 8 byte block sizes

**Comment by rat-moonshine** [comment]
@flashultra thank you, for response. If the usage are suppose to be same (PKCS5/7), perhaps you can give me some guidance to overcome the problem I'm facing (?)

With [Hurlant.Crypto](https://crypto.hurlant.com/) using same des-ecb and PKCS5 padding, I has following output with these key and values:

`trace(hurlant.encrypt(key:"rat-moonshine", value:"secretPassword")); // 79ZE94s1dA86up4W+A0Gpw==`

I was trying to decrypt that value (`79ZE94s1dA86up4W+A0Gpw==`) using `Des`:

```
var des:Des = new Des();
data = Bytes.ofHex("79ZE94s1dA86up4W+A0Gpw=="); // key: "rat-moonshine", value: "secretPassword"
data = des.decrypt(ECB, data, PKCS7);
trace("Decrypted text ECB: "+ data);
```
Unfortunately, it thrown following error on https://github.com/HaxeFoundation/crypto/blob/master/src/haxe/crypto/Des.hx#L329:
`[Fault] exception, information=TypeError: Error #1009: Cannot access a property or method of a null object reference.`

**Comment by flashultra** [comment]
Did you set the key for the Des (   ```des.init(key,iv)```  ) ? 
Also for Des key size is 56 bits and block size is 64 bits.  In your case the key is ```rat-moon``` ( as you can test here https://the-x.cn/en-US/cryptography/Des.aspx ) . Probably  Hurlant.Crypto cut part of the key when is more than 8 bytes

**Comment by rat-moonshine** [comment]
> Did you set the key for the Des ( des.init(key,iv) ) ?

No. Sorry, I was not clear about the usage but it make sense that we need to feed the _key_ some way.
During the decryption I only has once-encrypted value, and a key. 

Thank you, for the test-link (https://the-x.cn/en-US/cryptography/Des.aspx). It seems to decrypt correctly:
![image](https://user-images.githubusercontent.com/24370870/167440089-4e9b3172-769e-4b26-892e-d4c9f9ef8233.png)

This time with HaxeFoundation.Crypto, I catch a separate error from https://github.com/HaxeFoundation/crypto/blob/master/src/haxe/crypto/padding/PKCS7.hx#L24:

`[Fault] exception, information=Cannot remove 221 bytes, because message is 24 bytes`

Can you please check if I'm missing something again in my code (?):

```
var des:Des = new Des();
var key = Bytes.ofString("rat-moon");
des.init(key);

var data:Bytes = Bytes.ofString("79ZE94s1dA86up4W+A0Gpw==");
data = des.decrypt(ECB, data, PKCS7);
trace("Decrypted text ECB: "+ data);
```

**Comment by flashultra** [comment]
In your case you are using Base64 string as data. It should be 
```var data:Bytes = Base64.decode("79ZE94s1dA86up4W+A0Gpw==");```
not  ```Bytes.ofString(....)```

Here is a working example:
```haxe
               var key = Bytes.ofString("rat-moon");
		var des:Des = new Des(key);
		var data:Bytes = Base64.decode("79ZE94s1dA86up4W+A0Gpw==");
		data = des.decrypt(Mode.ECB, data, Padding.PKCS7);
		trace("Decrypted text ECB: "+ data);
```

**Comment by rat-moonshine** [comment]
Thank you, @flashultra ! That worked like a charm! 

Thank you very much for your timely help. It makes a lot of difference. )
