### ISSUE TITLE
Haxe-crypto

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/crypto#2]
Just found out about https://lib.haxe.org/p/haxe-crypto/
Maybe the work there should be merged with it ? we maybe don't need two crypto libraries.

**Comment by flashultra** [comment]
haxe-crypto is  port from crypto Hurlant AS3 library  ( http://crypto.hurlant.com/demo/ ) . 
It use class ByteArray ( port from class ByteArray from actionscript) . 
In my implementation I use only haxe Bytes class.
According to the main contributor , the project is not supported  from him any more   .
Also most of the classes already exist in haxe or haxe/crypto repository and other will require ByteArray class.   
 I'm not against adding crypto functions from there , but don't like idea to add additional class ByteArray and to reorganize current structure to fit with haxe-crypto .
For that reason I won't  rewrite code from haxe-crypto, but if someone else do pull request , I'll merge it.

**Comment by ncannasse** [comment]
I see. So the idea would be little by little to complete our library here with what this "not pure haxe" crypto library provides, but based on haxe.io.Bytes. Got it, and agree with you.

**Comment by flashultra** [comment]
My wish is to add Twofish and Bcrypt encryption first. After that maybe Blake2 or Ripemd-160. Will see. 
Do you looking for specific crypto function ?

Here is some comparison between crypto libraries: https://en.wikipedia.org/wiki/Comparison_of_cryptography_libraries
 But I think about 80% use only Aes, Blowfish or TripleDes . 

At the moment build still failed on Unicode test for Sha-224 and Sha-256 . 
 My first  assumption was about problem with  str2blks function, but it's not that.
It works with Haxe 4.0.0-preview.4+1e3e5e016 , but failed with latest development version. 
Still don't know where is the problem.

**Comment by flashultra** [comment]
Just to add something. RSA  required BigInteger support. At the moment thx,core have that class ( https://github.com/fponticelli/thx.core/blob/master/src/thx/BigInt.hx ) . 
 Do you think to add BigInteger as type to haxe std library ? 

JS version has about 400 K downloads per week ( https://www.npmjs.com/package/big-integer )

**Comment by kevinresol** [comment]
> Do you looking for specific crypto function ?

If I could answer this question: I would say RSA and ECDSA. 
They are useful for completing the [jwt](https://github.com/kevinresol/jsonwebtoken) implementation.

**Comment by flashultra** [comment]
I also think about that, but as I mention before this will require BigInteger support. 
 I don't  want to require install of thx.core , because this is more broadly library and also I'm looking to set crypto as independent from other libraries.  So there are three options:
 1) Add BigInteger in haxe std library
 2) Copy BigInteger implementation to crypto 
 3) Create new implementation of BigInteger
For me 1) is the most suitable solution, because BigInteger can be used across different projects.

**Comment by kevinresol** [comment]
For me I would say a separate library is the best choice. Just like the js one, single purposed.

**Comment by flashultra** [comment]
RSA and ECDSA are crypto algorithms , so my wish is to be in crypto library, but will see.

**Comment by kevinresol** [comment]
oh, I mean bigint should be in a separate library.
