### ISSUE TITLE
[Neko specific issue] Uncaught exception - load.c(398) : Invalid module : main.n

### ISSUE THREAD

**Issue by furretpaws** [HaxeFoundation/crypto#24]
Hello! I'm encountering an issue with the library. After successfully compiling the code, I'm trying to execute the resulting neko file. However, I'm getting an `Uncaught exception - load.c(398) : Invalid module : main.n` error. This seems to be a neko-specific issue rather than a problem with the library itself. This happened once I imported the `haxe.crypto.Poly1305` library into the project

Steps to reproduce:
1. Download the library using `haxelib git crypto https://github.com/HaxeFoundation/crypto`
2. Compile the code using `haxe -main Main --neko main.n -L crypto`.
3. Attempt to execute the neko file using `neko main.n`.
4. Get the `Uncaught exception - load.c(398) : Invalid module : main.n` error

Expected behavior:
The neko file should execute without any errors.

Actual behavior:
An `Uncaught exception - load.c(398) : Invalid module : main.n` error is encountered.

Additional information:
Operating system: Windows 10 22H2
Haxe version: 4.2.5
Neko version: 2.3.0

Any kind of help would be appreciated, thank you! :3

**Comment by tobil4sk** [comment]
The error message is vague but it could be:
https://github.com/HaxeFoundation/neko/issues/283

**Comment by flashultra** [comment]
Yes, this is the same issue described in https://github.com/HaxeFoundation/neko/issues/283
One solution could be the one suggested by @tobil4sk (using {} blocks).
I don't have time to make such a change, but you can create a pull request for such fix for Neko Poly1305 algorithm.
Also it is mark in the test file : https://github.com/HaxeFoundation/crypto/blob/master/tests/src/unit/TestMain.hx#L76

**Comment by flashultra** [comment]
As I mentioned earlier, I will accept the pull request to fix this problem, but there is nothing else I can do about this , so I will close the issue.

**Comment by furretpaws** [comment]
okay, i'll see what can i do about this, thank you anyways ^^
