### ISSUE TITLE
Sha256 Unicode test failed

### ISSUE THREAD

**Issue by flashultra** [HaxeFoundation/crypto#3]
I did some test with string  éあ😂  and this give different length 9 and 4 with different Haxe 4 version. 
What should be the correct length ?  I think this is the problem for Sha256 particulary here in s.length)  :
```haxe 
var h = sh.doEncode(str2blks(s), s.length*8);
```
**Sha256**
_Test string:_   éあ😂
_Length_: 9
_Version:_  Haxe 4.0.0-preview.4+1e3e5e016 
_Result :_  d0230b8d8ac2d6d0dbcee11ad0e0eaa68a6565347261871dc241571cab591676
Correct !

_Test string:_   éあ😂
_Length_: 4 
_Version:_  Haxe development
_Result :_  e662834bdc1a099b9f7b8d97975a1b1d9b6730c991268bba0e7fe7427e68be74
Incorrect

**Comment by flashultra** [comment]
Here https://mothereff.in/byte-counter for  éあ😂  get  3 characters and 9 Bytes as result.
Target: Interp
 
Total is 9 bytes (using  Bytes.ofString) . So what should return length ? Bytes or characters ? In both cases 4 is current development release is wrong.

 é   =  c3a9
あ  = e38182
😂  = f09f9882

**Comment by ncannasse** [comment]
You should only use latest Haxe GIT version that has correct handling for Unicode Strings. I still think on some platforms str2blks does give invalid results because of surrogate pairs (#if utf16)

**Comment by ncannasse** [comment]
We should instead use  haxe.io.Bytes.fromString that correctly gives UTF8 bytes. Another option would be a way to iterate on Unicode chars without surrogate pairs but we don't have such API atm.

**Comment by ncannasse** [comment]
9 Bytes is correct, you will get c3a9e38182f09f9882 in Hexadecimal with is
the UTF8 representation of the string. String length can be 3 or 4
depending if   😂 is encoded as surrogate pair or not

**Comment by flashultra** [comment]
The current Sha256 require length in bytes. Is it possible to get length in bytes instead count of character ?
The only way to do that now is 
```
 var l = Bytes.ofString(s).length;
```
but this is  some sort of hack. Not sure if anyone else will want to use bytes length instead of count character, but maybe it's possible to be add some other function for that.
About javascript according to specification can use UCS-2 and UTF-16 and most java frameworks used utf-16

**Comment by ncannasse** [comment]
What's the length in bytes ? it is encoding dependent. In order to know the length in bytes using UTF8 encoding then yes Bytes.ofString(s).length is one way. Another is to iterate on String char and check in how many bytes they will be encoded in UTF8

**Comment by flashultra** [comment]
Fixed. Most SHA 256 use UTF8 as string input.  I add Encoding param, so default should be UTF-8, but can use any of haxe support encoding.
 Also I use Bytes.ofString  and replace str2blks , so should work with UTF-16 .

Here are example for different encodings ( from stackoverflow https://stackoverflow.com/questions/39589999/correct-sha256-implementation-with-utf-8-characters?rq=1 )

  "í" in Windows-1252 is byte ED, which hashes as:
f3df1f9c358ae8eceb8fce7c00614288d113ad55315f4ebb909774a7daadfc84

"í" in UTF-8 is bytes C3 AD, which hashes as:
127035a8ff26256ea0541b5add6dcc3ecdaeea603e606f84e0fd63492fbab2c5

"í" in UTF-16LE is bytes ED 00, which hashes as:
430e2ca27910b5ee6e0ec56a12b81325c763376cb8e25a60362dce9444424f95
