### ISSUE TITLE
BCrypt is too slow

### ISSUE THREAD

**Issue by flashultra** [HaxeFoundation/crypto#4]
BCrypt is way too  slow . For rounds=10   should give  ~10 hashes/sec , now give 1 hash for 10 sec.

These is because Feistel function  ( i.e.  **f( x : Int )**  ) . 
For some reason bit shift operation are too slow in Haxe or it's maybe other specific issue.

Simple bcrypt hash  for 10 rounds with salt = $2a$10$/OxwMgmw06Zkhz/SLgc.4u  and text = some_text  will take about 10 seconds. 
Final result is : $2a$10$/OxwMgmw06Zkhz/SLgc.4uYyFJfaVs5/O.1.8Z9dPYIDxio8Jpc6W

**Comment by flashultra** [comment]
It's possible to be something eval target specific. On try.haxe ( js target ) is about 0.12 sec. 
https://try.haxe.org/#0c7a7  , same on try-mrcdk ( http://try-haxe.mrcdk.com/#e6074 ) with latest haxe dev

**Comment by Simn** [comment]
Can you factor out some code that executes slowly so I can take a look?

**Comment by flashultra** [comment]
Sorry, maybe is not so clean code, but here is example:  https://try.haxe.org/#ed87F
The problem is with  **function f(x:Int)**
On eval I get : 
 **Time: 5.0531008243560791** seconds
For JS : 
  **Time: 0.6010000705718994** seconds

**Comment by Simn** [comment]
Well, we have to put things in perspective here:

target   | time
-------- | ----
python | 51.3
hlinterp | 29.7
flash     | 12.4
php      | 11.4
neko     | 5.2
eval       | 4.9

Of course a number cruncher like this is going to be slow on targets that don't have a static compilation or a crazy JIT like JS does.

**Comment by Simn** [comment]
You can bring this down to 3.7 by making `f` and `sBox` static. Eval has trouble optimizing instance calls because it can't be sure if a function is overridden or not. Technically, I can't even rely on `final` for that because there's this goddamn `@:hack` thing.

**Comment by hughsando** [comment]
would 'inline' help?  That should make it un@:hackable

**Comment by Simn** [comment]
Sure, but then there's no call left for me to optimize.

From Nicolas reaction, it seemed like we don't have to consider `@:hack`. We might want to restrict it to externs.

**Comment by hughsando** [comment]
Yes, it would be sad not being allowed to optimize anything.

**Comment by Simn** [comment]
I just checked, `@:hack` only works on classes, not on fields. So checking `cf_final` is safe, we just can't check for `cl_final` until we address https://github.com/HaxeFoundation/haxe/issues/7473.

**Comment by flashultra** [comment]
Using Vector give some performance boost . Nothing else can do here .
