### ISSUE TITLE
[eval] Ripemd-160 test failed on Appveyor

### ISSUE THREAD

**Issue by flashultra** [HaxeFoundation/crypto#5]
First word from the test pass, all other failed.
The problem is not reproducible  from my side ( on my PC ) and for that reason don't know how to fix it.
The only things which is different is using of **BytesBuffer** class and clear with  **new BytesBuffer();**

**Comment by Simn** [comment]
I cannot reproduce that locally either.

**Comment by Simn** [comment]
That `clear()` function doesn't do anything with `bytesBuffer` though.
