### ISSUE TITLE
Compatibility for Haxe 3

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/crypto#6]
Can I expect this library _should_ work with haxe 3?

**Comment by flashultra** [comment]
Yes, it should works. The only problem will be a specific bugs in haxe3 ( at example in php target and maybe eval).  There is nothing specific in use from Haxe 4.

**Comment by kevinresol** [comment]
There some haxe 4 features in the Sha*** classes (`extern` keyword and `haxe.io.Encoding`)

**Comment by flashultra** [comment]
Extern in Sha256 is from original haxe crypto branch ( https://github.com/HaxeFoundation/haxe/blob/development/std/haxe/crypto/Sha256.hx ) 
About Encoding, yes you a right. I added that option so different encoding  can be used  in Bytes.ofString method.
There are some solution for both problems:
 1) Discard support for Haxe 3 
 2) Add compiler flag to support Haxe 3
 3) Remove extern and Encoding.
I think all other classes should works. The main question is how widely use will be Haxe 3 i.e Sha224 and Sha256 exist in haxe.crypto package in Haxe 3.XX  and obviously at the moment no one looking for Sha384 and Sha512 in Haxe3.

**Comment by grepsuzette** [comment]
There is use for Sha512 even in Haxe 3. I had been using some ugly calls to the system for that before using your classes. I’m sure there are others in the same boat.

It would be a shame given the very minor adjustments and the great work done here to not make this package compatible with Haxe 3. Even though we can always fork the repo and make the adjustements ourself (did that myself and I hate it for the reason that follows), those classes are about security, and in the end it's critical for not missing updates that we don't encourage having many forks in the wild by not supporting Haxe 3.

Haxe 4 is just sugar (and not yet stable), the features provided by those classes on the other hand are critical for some tasks. Supporting both (even partially, but still with the ShaXXX) would be ideal.

**Comment by flashultra** [comment]
All classes are now compatible ( see pull request https://github.com/HaxeFoundation/crypto/pull/11)
