### ISSUE TITLE
Use Vector instead of Array

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/crypto#9]
E.g. here: https://github.com/HaxeFoundation/crypto/blob/master/src/haxe/crypto/Aes.hx#L10

Vector is significantly faster on some targets.

**Comment by flashultra** [comment]
I'm planing to do this. At the moment vector copy() method  ( for JS  target)  use blit() not slice() which give worse performance  ( related to https://github.com/HaxeFoundation/haxe/issues/8040#issuecomment-476591845)

**Comment by flashultra** [comment]
Done. Get performance boost mostly fot Java , C# and Python. 
Here are some test values for Java:
           
         New  vs Old
         BlowFish - 0.92s vs 2.89s
         Ripemd160 - 0.80s vs 1.01s
         TwoFish - 0.12s vs 0.22s
         TripleDes - 1.88s vs 3.48s
         Sha512 - 0.16s vs 0.21s
         Sha384 - 0.13s vs 0.22s
         Sha256 - 0.11 vs 0.19s
         Sha224 - 0.13s vs 0.20s
